# Generated by Django 5.2.11 on 2026-02-04 07:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_gram', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_baht', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='THB', max_length=3)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Price History',
                'verbose_name_plural': 'Price History',
                'db_table': 'price_history',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='GoldHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=10)),
                ('avg_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gold_holdings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gold Holding',
                'verbose_name_plural': 'Gold Holdings',
                'db_table': 'gold_holdings',
                'ordering': ['-updated_at'],
            },
        ),
    ]
